name: Github Snake Game

on:
  # Schedule the workflow to run daily at 00:00 UTC

  schedule:
    - cron: '0 0 * * *'

  # Allow manually triggering of the workflow
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository

      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Github Contributions Snake Animations
        uses:
          # Github username to generate the animation for
          github_username: ${{ github.repository_owner }}

          # Define the output file and their configurations

          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6, #8dbdff, #64a1f4, #4b91f1, #3c7dd9

          env:
            # Github token to authenticate the action
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch

        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: 'Update snake animation'